Install kitty if not installed, add windows listing with jq if installed

diff --git a/install b/install
--- a/install
+++ b/install
@@ -4,11 +4,131 @@ SCRIPT_PATH="$( cd "$(dirname "$0")" ; pwd -P )"
 SCRIPT_PATH="$(realpath "$SCRIPT_PATH")"
 REPO_URL="https://github.com/doctorfree/kitty-control"
 
-have_git=$(type -p git)
-[ "${have_git}" ] || {
-  printf "\nERROR: cannot locate required git command"
-  printf "\nInstall git and re-run this install script\n\n"
-  exit 1
+install_kitty() {
+  if [ "${darwin}" ]; then
+    LOCAL="/Applications/kitty.app/Contents"
+    KBIN="${LOCAL}/MacOS"
+    KTINFO="${LOCAL}/Resources/kitty/terminfo/kitty.terminfo"
+    KXTERM="${LOCAL}/Resources/kitty/terminfo/78/xterm-kitty"
+    KSTERM="${LOCAL}/Resources/terminfo/78/xterm-kitty"
+  else
+    LOCAL="${HOME}/.local/kitty.app"
+    KBIN="${LOCAL}/bin"
+    KTINFO="${LOCAL}/lib/kitty/terminfo/kitty.terminfo"
+    KXTERM="${LOCAL}/lib/kitty/terminfo/x/xterm-kitty"
+    KSTERM="${LOCAL}/share/terminfo/x/xterm-kitty"
+  fi
+  printf "\n\tInstalling Kitty terminal emulator ..."
+  installer_url="https://sw.kovidgoyal.net/kitty/installer.sh"
+  curl --silent --location ${installer_url} >/tmp/kitty-$$.sh
+  [ $? -eq 0 ] || {
+    rm -f /tmp/kitty-$$.sh
+    curl --insecure --silent --location ${installer_url} >/tmp/kitty-$$.sh
+    cat /tmp/kitty-$$.sh | sed -e "s/curl -/curl -k/" >/tmp/k$$
+    cp /tmp/k$$ /tmp/kitty-$$.sh
+    rm -f /tmp/k$$
+  }
+  if [ -s /tmp/kitty-$$.sh ]; then
+    sh /tmp/kitty-$$.sh launch=n >/dev/null 2>&1
+    rm -f /tmp/kitty-$$.sh
+    # Create a symbolic link to add kitty to PATH
+    [ -d ~/.local/bin ] || mkdir -p ~/.local/bin
+    if [ -x ${KBIN}/kitty ]; then
+      [ -x ~/.local/bin/kitty ] || {
+        ln -s ${KBIN}/kitty ~/.local/bin/
+      }
+    else
+      printf "\nUnable to create Kitty link to ~/.local/bin/\n"
+    fi
+    if [ -x ~/${KBIN}/kitten ]; then
+      [ -x ~/.local/bin/kitten ] || {
+        ln -s ~/${KBIN}/kitten ~/.local/bin/
+      }
+    else
+      printf "\nUnable to create kitten link to ~/.local/bin/\n"
+    fi
+    # Link the kitty man pages somewhere it can be found by the man command
+    if [ "${darwin}" ]; then
+      LINMAN="/Applications/kitty.app/Contents/Resources/man"
+    else
+      LINMAN="${LOCAL}/share/man"
+    fi
+    [ -d ~/.local/share/man/man1 ] || mkdir -p ~/.local/share/man/man1
+    [ -f ~/.local/share/man/man1/kitty.1 ] || {
+      [ -d ${HOME}/.local/share/man/man1 ] || {
+        mkdir -p ${HOME}/.local/share/man/man1
+      }
+      [ -f "${LINMAN}/man1/kitty.1" ] && {
+        ln -s "${LINMAN}/man1/kitty.1" ~/.local/share/man/man1/
+      }
+    }
+    [ -d ~/.local/share/man/man5 ] || mkdir -p ~/.local/share/man/man5
+    [ -f ~/.local/share/man/man5/kitty.conf.5 ] || {
+      [ -d ${HOME}/.local/share/man/man5 ] || {
+        mkdir -p ${HOME}/.local/share/man/man5
+      }
+      [ -f "${LINMAN}/man5/kitty.conf.5" ] && {
+        ln -s "${LINMAN}/man5/kitty.conf.5" ~/.local/share/man/man5/
+      }
+    }
+    # Place the kitty.desktop file somewhere it can be found by the OS
+    [ -d ~/.local/share/applications ] || mkdir -p ~/.local/share/applications
+    [ -f "${LOCAL}/share/applications/kitty.desktop" ] && {
+      [ -f ~/.local/share/applications/kitty.desktop ] || {
+        cp ${LOCAL}/share/applications/kitty.desktop \
+          ~/.local/share/applications/
+      }
+    }
+    # If you want to open text files and images in kitty via your file manager
+    # also add the kitty-open.desktop file
+    [ -f "${LOCAL}/share/applications/kitty-open.desktop" ] && {
+      [ -f ~/.local/share/applications/kitty-open.desktop ] || {
+        cp ${LOCAL}/share/applications/kitty-open.desktop \
+          ~/.local/share/applications/
+      }
+    }
+    # Update the paths to the kitty and its icon in the kitty.desktop file(s)
+    for desktop in "${HOME}"/.local/share/applications/kitty*.desktop; do
+      [ "${desktop}" == "${HOME}/.local/share/applications/kitty*.desktop" ] && continue
+      [ -f ${LOCAL}/share/icons/hicolor/256x256/apps/kitty.png ] && {
+        sed -i "s|Icon=kitty|Icon=${LOCAL}/share/icons/hicolor/256x256/apps/kitty.png|g" "${desktop}"
+      }
+      [ -x ${LOCAL}/bin/kitty ] && {
+        sed -i "s|Exec=kitty|Exec=${LOCAL}/bin/kitty|g" "${desktop}"
+      }
+    done
+    printf " done!\n"
+  else
+    printf "\n${BOLD}ERROR:${NORM} Download of kitty installation script failed"
+    printf "\nSee https://sw.kovidgoyal.net/kitty/binary/#manually-installing"
+    printf "\nto manually install the kitty terminal emulator\n"
+  fi
+
+  # Install the Kitty terminfo entry
+  KITERM="${HOME}/.terminfo/x/xterm-kitty"
+  MATERM="${HOME}/.terminfo/78/xterm-kitty"
+  [ -f "${KITERM}" ] || [ -f "${MATERM}" ] || {
+    [ -d ${HOME}/.terminfo ] || mkdir -p ${HOME}/.terminfo
+    [ -d ${HOME}/.terminfo/x ] || mkdir -p ${HOME}/.terminfo/x
+    [ -d ${HOME}/.terminfo/78 ] || mkdir -p ${HOME}/.terminfo/78
+    have_tic=$(type -p tic)
+    [ "${have_tic}" ] && {
+      [ -f "${KTINFO}" ] && {
+        tic -x -o ${HOME}/.terminfo "${KTINFO}" >/dev/null 2>&1
+      }
+    }
+    [ -f "${KITERM}" ] || [ -f "${MATERM}" ] || {
+      if [ -f "${KXTERM}" ]; then
+        cp "${KXTERM}" "${KITERM}"
+      else
+        if [ -f "${KSTERM}" ]; then
+          cp "${KSTERM}" "${KITERM}"
+        else
+          printf "\nUnable to create Kitty terminfo entry ${KITERM}\n"
+        fi
+      fi
+    }
+  }
 }
 
 install_config() {
@@ -39,6 +159,21 @@ install_config() {
     }
   }
 }
+
+have_git=$(type -p git)
+[ "${have_git}" ] || {
+  printf "\nERROR: cannot locate required git command"
+  printf "\nInstall git and re-run this install script\n\n"
+  exit 1
+}
+
+export PATH="${HOME}/.local/bin:${PATH}"
+darwin=
+platform=$(uname -s)
+[ "${platform}" == "Darwin" ] && darwin=1
+
+have_kitty=$(type -p kitty)
+[ "${have_kitty}" ] || install_kitty
 
 # If standalone install, clone the repository, run the install script, exit
 [ -f "${SCRIPT_PATH}"/kitty-control ] || {
