Flesh out menu system, install fzf

diff --git a/kitty-control b/kitty-control
--- a/kitty-control
+++ b/kitty-control
@@ -36,8 +36,12 @@ FONTDIR="${HOME}/.local/share/figlet-fonts"
 LOLCAT="lolcat"
 # Array with font names
 fonts=("Fire Font-k" "Graceful" "Script" "Shadow" "Slant" "Small" "Standard")
+# Font size choices for menu
+fontsizes=("default" "+1" "+2" "+4" "+8" "+12" "-1" "-2" "-4" "-8" "-12")
 # Transparency opacity choices for menu
-translevels=("default" "0.0" "0.1" "0.2" "0.3" "0.4" "0.5" "0.6" "0.7" "0.8" "0.9" "1.0")
+translevels=("default" "1.0" "0.9" "0.8" "0.7" "0.6" "0.5" "0.4" "0.3" "0.2" "0.1" "0.0")
+# Colors
+colors=("reset" "black" "white" "red" "green" "yellow" "blue" "magenta" "cyan")
 # Use tput to get the bold and normal text sequence
 BOLD=$(tput bold 2>/dev/null)
 NORM=$(tput sgr0 2>/dev/null)
@@ -60,7 +64,6 @@ brief_usage() {
 }
 
 show_examples() {
-  brief_usage noexit
   printf "\nExample invocations of kitty-control\n"
   printf "\nTo set a transparent Kitty background with 0.9 opacity:"
   printf "\n\t${BOLD}kitty-control transparent 0.9${NORM}"
@@ -386,10 +389,121 @@ prompt_continue() {
   read -r yn
 }
 
+choose_file() {
+  TMP="$(mktemp)"
+  ranger --choosefile="${TMP}" "${HOME}" 1>&2
+  cat ${TMP}
+  rm -f ${TMP}
+}
+
+choose_folder() {
+  TMP="$(mktemp)"
+  ranger --choosedir="${TMP}" "${HOME}" 1>&2
+  cat ${TMP}
+  rm -f ${TMP}
+}
+
+select_file() {
+  # Can be called with e.g. 'select_file image' to use 'image' as file type
+  # If no argument is passed then any file will do
+  keyword=
+  selectedFile=
+  [ "$1" ] && keyword="$1"
+  if [ "${have_ranger}" ]; then
+    selectedFile="$(choose_file)"
+  else
+#   selectedFile=$(dialog --stdout --title "Please select a file" --fselect ${HOME} 0 0)
+    printf "\nEnter the path to a file\n"
+    while true; do
+      read -r -p "Enter file path ('q' to exit): " filepath
+      [ "${filepath}" == "q" ] && break
+      if [ -f "${filepath}" ]; then
+        selectedFile="${filepath}"
+        break
+      else
+        if [ "${filepath}" ]; then
+          printf "Specified file ${filepath} does not exist or is not a plain file."
+        else
+          printf "\nEmpty file path entered."
+        fi
+        printf "\nPlease enter a valid file path or 'q' to exit this dialog.\n"
+      fi
+    done
+  fi
+  if [ "${selectedFile}" ]; then
+    if [ "${keyword}" ]; then
+      thisfile=
+      file "${selectedFile}" | grep -i "${keyword}" >/dev/null && thisfile=1
+    else
+      thisfile=1
+    fi
+    [ "${thisfile}" ] && FILE="${selectedFile}"
+  else
+    FILE=
+  fi
+}
+
+select_folder() {
+  FOLD=
+  if [ "${have_ranger}" ]; then
+    echo ""
+    echo "Choosing a directory in Ranger is done by visiting a directory"
+    echo ""
+    echo "Use the arrow keys to browse folders"
+    echo "Press 'Enter' to enter a directory"
+    echo "Create a new directory with ':mkdir <dirname>'"
+    echo ""
+    echo "While in the directory you wish to select, quit Ranger with 'q'"
+    echo ""
+    while true; do
+      read -p "Select directory now? (y/n) " answer
+      case ${answer} in
+        [Yy]*)
+          FOLD="$(choose_folder)"
+          echo ""
+          echo "Selected directory = ${FOLD}"
+          echo ""
+          break
+          ;;
+        [Nn]*)
+          printf "\nSkipping directory selection.\n"
+          FOLD=
+          break
+          ;;
+        *)
+          echo "Please answer 'y' to select directory, or 'n' to skip."
+          ;;
+      esac
+    done
+  else
+#   FOLD=$(dialog --stdout \
+#                 --title "Please select an image input folder" \
+#                 --fselect ${HOME}/ 14 48)
+    printf "\nEnter the path to a directory\n"
+    while true; do
+      read -r -p "Enter directory path ('q' to exit): " foldpath
+      [ "${foldpath}" == "q" ] && break
+      if [ -d "${foldpath}" ]; then
+        FOLD="${foldpath}"
+        break
+      else
+        if [ "${foldpath}" ]; then
+          printf "Specified directory ${foldpath} does not exist or is not a directory."
+        else
+          printf "\nEmpty directory path entered."
+        fi
+        printf "\nPlease enter a valid directory path or 'q' to exit this dialog.\n"
+      fi
+    done
+  fi
+}
+
+
 set_haves() {
   have_fzf=$(type -p fzf)
   have_figlet=$(type -p figlet)
   have_lolcat=$(type -p lolcat)
+  have_ranger=$(type -p ranger)
   have_rich=$(type -p rich)
 }
 
@@ -411,15 +525,22 @@ show_figlet() {
 }
 
 show_usage() {
+  use_type="$1"
+  figlet_text="Usage"
+  [ "${use_type}" == "examples" ] && figlet_text="Examples"
   while true; do
     clear
     if [ "${have_figlet}" ]; then
-      show_figlet "Usage"
+      show_figlet "${figlet_text}"
     else
-      [ "${have_rich}" ] && rich "[cyan]Usage[/cyan]" -p -a rounded -c -C
+      [ "${have_rich}" ] && rich "[cyan]${figlet_text}[/cyan]" -p -a rounded -c -C
     fi
     printf "\n"
-    brief_usage noexit
+    if [ "${use_type}" == "examples" ]; then
+      show_examples noexit | less
+    else
+      brief_usage noexit
+    fi
     printf "\n\n"
     options=()
     PS3="${BOLD}Enter a choice (number, shortcut, or text, 'h' help): ${NORM}"
@@ -461,16 +582,9 @@ show_menu() {
     else
       [ "${have_rich}" ] && rich "[cyan]Kitty Control[/cyan]" -p -a rounded -c -C
     fi
+    printf "\n"
     options=()
     PS3="${BOLD}Enter a choice (number, shortcut, or text, 'h' help): ${NORM}"
-# Usage: kitty-control [-a] [-c command] [-e] [-i /path/to/image]
-# [-m|t <match>] [-s /path/to/socket] [-u|h|v] [back <color>]
-# [diff [opts] <path1> <path2>] [fore <color>] [font [num]]
-# [icat [opts] <image>] [title <title>]
-# 
-#  display several examples run 'kitty-control -e'
-#  a full usage message run 'kitty-control -u'
-#  a full usage message with examples run 'kitty-control -h'
     numconfs=1
     configs=("default")
     for kconf in ${CONFDIR}/*/kitty.conf
@@ -479,12 +593,15 @@ show_menu() {
       ((numconfs++))
       configs+=("${kconf}")
     done
+    options+=("Background Color" "Background Image" "Clear Background Image")
+    options+=("Dark/Opaque" "Diff Files" "Diff Folders" "Examples" "Font Size")
+    options+=("Foreground Color" "List Current Info")
     [ ${numconfs} -gt 1 ] && {
       options+=("Load Kitty Configuration")
     }
-    options+=("Dark/Opaque" "List Current Info" "Transparent" "Toggle Fullscreen")
-    options+=("Theme Selection" "Terminal Info" "Unicode Input" "Show Usage Message")
-    options+=("Upgrade Kitty" "Quit (q)")
+    options+=("Show Usage Message" "Theme Selection")
+    options+=("Terminal Info" "Toggle Fullscreen" "Transparent" "Unicode Input")
+    options+=("Upgrade Kitty" "View an Image" "Quit (q)")
     select opt in "${options[@]}"; do
       case "$opt,$REPLY" in
       "h",* | *,"h" | "H",* | *,"H" | "help",* | *,"help" | "Help",* | *,"Help")
@@ -492,8 +609,129 @@ show_menu() {
         show_help
         break
         ;;
+      "Background Color",* | *,"Background Color")
+        if [ "${have_fzf}" ]; then
+          choice=$(printf "%s\n" "${colors[@]}" | fzf --prompt="😺 Select Background Color  " --layout=reverse --border --exit-0)
+          [ "${choice}" ] && {
+            forepre=$(kitty @ get-colors | grep "^foreground" | awk '{ print $2 }')
+            backpre=$(kitty @ get-colors | grep "^background" | awk '{ print $2 }')
+            set-background "${choice}"
+            case "${choice}" in
+              black)
+                set-foreground white
+                ;;
+              white)
+                set-foreground black
+                ;;
+              *)
+                true
+                ;;
+            esac
+            forecolor=$(kitty @ get-colors | grep "^foreground" | awk '{ print $2 }')
+            backcolor=$(kitty @ get-colors | grep "^background" | awk '{ print $2 }')
+            [ "${forecolor}" == "${backcolor}" ] && {
+              set-foreground "${forepre}"
+              set-background "${backpre}"
+            }
+          }
+        else
+          printf "\nERROR: Cannot locate required fzf fuzzy finder"
+          printf "\nTo set Kitty background color using the Kitty Control"
+          printf "\nmenu system. Install fzf and re-run kitty-control\n"
+          prompt_continue
+        fi
+        break
+        ;;
+      "Foreground Color",* | *,"Foreground Color")
+        if [ "${have_fzf}" ]; then
+          choice=$(printf "%s\n" "${colors[@]}" | fzf --prompt="😺 Select Foreground Color  " --layout=reverse --border --exit-0)
+          [ "${choice}" ] && {
+            forepre=$(kitty @ get-colors | grep "^foreground" | awk '{ print $2 }')
+            backpre=$(kitty @ get-colors | grep "^background" | awk '{ print $2 }')
+            set-foreground "${choice}"
+            forecolor=$(kitty @ get-colors | grep "^foreground" | awk '{ print $2 }')
+            backcolor=$(kitty @ get-colors | grep "^background" | awk '{ print $2 }')
+            [ "${forecolor}" == "${backcolor}" ] && {
+              set-foreground "${forepre}"
+              set-background "${backpre}"
+            }
+          }
+        else
+          printf "\nERROR: Cannot locate required fzf fuzzy finder"
+          printf "\nTo set Kitty foreground color using the Kitty Control"
+          printf "\nmenu system. Install fzf and re-run kitty-control\n"
+          prompt_continue
+        fi
+        break
+        ;;
+      "Background Image",* | *,"Background Image")
+        FILE=
+        select_file image
+        [ "${FILE}" ] && kitty @ ${SOCKET} set-background-image ${OPTS} "${FILE}"
+        break
+        ;;
+      "Clear Background Image",* | *,"Clear Background Image")
+        kitty @ ${SOCKET} set-background-image ${OPTS} none
+        break
+        ;;
       "Dark"*,* | *,"Dark"* | "dark"*,* | *,"dark"* | "Opaq"*,* | *,"Opaq"* | "opaq"*,* | *,"opaq"*)
         set-opacity "1.0"
+        break
+        ;;
+      "Diff File"*,* | *,"Diff File"* | "diff file"*,* | *,"diff file"*)
+        FILE=
+        file1=
+        file2=
+        select_file
+        [ "${FILE}" ] && {
+          file1="${FILE}"
+          select_file
+          [ "${FILE}" ] && {
+            file2="${FILE}"
+          }
+        }
+        [ "${file1}" ] && [ "${file2}" ] && {
+          kitty +kitten diff "${file1}" "${file2}"
+        }
+        break
+        ;;
+      "Diff Fold"*,* | *,"Diff Fold"* | "diff fold"*,* | *,"diff fold"*)
+        FOLD=
+        fold1=
+        fold2=
+        select_folder
+        [ "${FOLD}" ] && {
+          fold1="${FOLD}"
+          select_folder
+          [ "${FOLD}" ] && {
+            fold2="${FOLD}"
+          }
+        }
+        [ "${fold1}" ] && [ "${fold2}" ] && {
+          kitty +kitten diff "${fold1}" "${fold2}"
+        }
+        break
+        ;;
+      "Exam"*,* | *,"Exam"* | "exam"*,* | *,"exam"*)
+        show_usage examples
+        break
+        ;;
+      "Font"*,* | *,"Font"* | "font"*,* | *,"font"*)
+        if [ "${have_fzf}" ]; then
+          choice=$(printf "%s\n" "${fontsizes[@]}" | fzf --prompt="😺 Select Font Size Adjustment  " --layout=reverse --border --exit-0)
+          [ "${choice}" ] && {
+            if [ "${choice}" == "default" ]; then
+              kitty-fontsize 0
+            else
+              kitty-fontsize "${choice}"
+            fi
+          }
+        else
+          printf "\nERROR: Cannot locate required fzf fuzzy finder"
+          printf "\nTo set Kitty font size using the Kitty Control"
+          printf "\nmenu system. Install fzf and re-run kitty-control\n"
+          prompt_continue
+        fi
         break
         ;;
       "List"*,* | *,"List"* | "list"*,* | *,"list"*)
@@ -514,9 +752,19 @@ show_menu() {
         else
           printf "\nERROR: Cannot locate required fzf fuzzy finder"
           printf "\nTo load Kitty configurations using the Kitty Control"
-          printf "\nmenu system install fzf and re-run kitty-control\n"
+          printf "\nmenu system. Install fzf and re-run kitty-control\n"
           prompt_continue
         fi
+        break
+        ;;
+      "View"*,* | *,"View"* | "view"*,* | *,"view"*)
+        FILE=
+        select_file image
+        [ "${FILE}" ] && {
+          kitty +kitten icat ${FILE}
+          printf "\nTo view this image use: kitty +kitten icat ${FILE}\n"
+          prompt_continue
+        }
         break
         ;;
       "Theme"*,* | *,"Theme"* | "theme"*,* | *,"theme"*)
@@ -541,7 +789,7 @@ show_menu() {
         else
           printf "\nERROR: Cannot locate required fzf fuzzy finder"
           printf "\nTo set Kitty transparency using the Kitty Control"
-          printf "\nmenu system install fzf and re-run kitty-control\n"
+          printf "\nmenu system. Install fzf and re-run kitty-control\n"
           prompt_continue
         fi
         break
@@ -556,7 +804,7 @@ show_menu() {
         break
         ;;
       "Show"*,* | *,"Show"* | "show"*,* | *,"show"*)
-        show_usage
+        show_usage usage
         break
         ;;
       "Manual"*,* | *,"Manual"* | "manual"*,* | *,"manual"*)
