Add support for upgrades to both kitty and kitty-control

diff --git a/kitty-control b/kitty-control
--- a/kitty-control
+++ b/kitty-control
@@ -9,7 +9,7 @@
 # Written Feb 1, 2024 by Ronald Joe Record <ronaldrecord@gmail.com>
 #
 VERSION=1.0.2
-RELEASE=2
+RELEASE=1
 # The Kitty configuration directory
 CONFDIR="${HOME}/.config/kitty"
 [ "${KITTY_CONFIG_DIRECTORY}" ] && {
@@ -171,7 +171,7 @@ usage() {
   [ "$1" == "noexit" ] || exit 1
 }
 
-check_control_version() {
+get_control_version() {
   VTOP="https://raw.githubusercontent.com/doctorfree/kitty-control"
   VURL="${VTOP}/main/VERSION"
   curl -fsSL "${VURL}" > /tmp/kcv$$
@@ -181,26 +181,37 @@ check_control_version() {
   echo "v${kcver}r${kcrel}"
 }
 
-get_release_version() {
-  release_version=$(curl -fsSL "https://sw.kovidgoyal.net/kitty/current-version.txt")
-  echo "${release_version}"
+get_install_version() {
+  KC_INST="${HOME}/.local/bin/kitty-control"
+  if [ -f ${KC_INST} ]; then
+    kcver=$(grep ^VERSION= ${KC_INST} | awk -F '=' '{ print $2 }')
+    kcrel=$(grep ^RELEASE= ${KC_INST} | awk -F '=' '{ print $2 }')
+  else
+    kcver=${VERSION}
+    kcrel=${RELEASE}
+  fi
+  echo "v${kcver}r${kcrel}"
 }
 
+# check_kitty_version release_version install_version
 check_kitty_version() {
-  release_version=$(get_release_version)
+  release_version="$1"
+  install_version="$2"
+
   release_major=$(echo ${release_version} | awk -F '.' '{ print $1 }')
   release_midde=$(echo ${release_version} | awk -F '.' '{ print $2 }')
   release_minor=$(echo ${release_version} | awk -F '.' '{ print $3 }')
   [ "${release_major}" ] || release_major=0
   [ "${release_midde}" ] || release_midde=0
   [ "${release_minor}" ] || release_minor=0
-  install_version=$(kitty --version | awk '{ print $2 }')
+
   install_major=$(echo ${install_version} | awk -F '.' '{ print $1 }')
   install_midde=$(echo ${install_version} | awk -F '.' '{ print $2 }')
   install_minor=$(echo ${install_version} | awk -F '.' '{ print $3 }')
   [ "${install_major}" ] || install_major=0
   [ "${install_midde}" ] || install_midde=0
   [ "${install_minor}" ] || install_minor=0
+
   if [ ${release_major} -gt ${install_major} ]; then
     echo "${release_version}"
   else
@@ -216,11 +227,51 @@ check_kitty_version() {
   fi
 }
 
+# check_control_version release_version install_version
+check_control_version() {
+  release_version=$(echo $1 | awk -F 'r' '{ print $1 }' | sed -e "s/v//")
+  release_release=$(echo $1 | awk -F 'r' '{ print $2 }')
+  install_version=$(echo $2 | awk -F 'r' '{ print $1 }' | sed -e "s/v//")
+  install_release=$(echo $2 | awk -F 'r' '{ print $2 }')
+  release_major=$(echo ${release_version} | awk -F '.' '{ print $1 }')
+  release_midde=$(echo ${release_version} | awk -F '.' '{ print $2 }')
+  release_minor=$(echo ${release_version} | awk -F '.' '{ print $3 }')
+  [ "${release_major}" ] || release_major=0
+  [ "${release_midde}" ] || release_midde=0
+  [ "${release_minor}" ] || release_minor=0
+  [ "${release_release}" ] || release_release=0
+  install_major=$(echo ${install_version} | awk -F '.' '{ print $1 }')
+  install_midde=$(echo ${install_version} | awk -F '.' '{ print $2 }')
+  install_minor=$(echo ${install_version} | awk -F '.' '{ print $3 }')
+  [ "${install_major}" ] || install_major=0
+  [ "${install_midde}" ] || install_midde=0
+  [ "${install_minor}" ] || install_minor=0
+  [ "${install_release}" ] || install_release=0
+  if [ ${release_major} -gt ${install_major} ]; then
+    echo "${release_version}"
+  else
+    if [ ${release_midde} -gt ${install_midde} ]; then
+      echo "${release_version}"
+    else
+      if [ ${release_minor} -gt ${install_minor} ]; then
+        echo "${release_version}"
+      else
+        if [ ${release_release} -gt ${install_release} ]; then
+          echo "${release_version}"
+        else
+          echo ""
+        fi
+      fi
+    fi
+  fi
+}
+
 show_versions() {
-  control_version=$(check_control_version)
+  control_version=$(get_control_version)
   printf "\nInstalled kitty-control version: v${VERSION}r${RELEASE}"
   printf "\nAvailable kitty-control version: ${control_version}"
   release_version=$(get_release_version)
+  release_version=$(curl -fsSL "https://sw.kovidgoyal.net/kitty/current-version.txt")
   install_version=$(kitty --version | awk '{ print $2 }')
   printf "\nInstalled kitty version: ${install_version}"
   printf "\nAvailable kitty version: ${release_version}\n\n"
@@ -230,7 +281,7 @@ install_figlet() {
   have_make=$(type -p make)
   if [ "${have_make}" ]; then
     HERE=$(pwd)
-    git clone https://github.com/cmatsuoka/figlet /tmp/figlet$$
+    git clone https://github.com/cmatsuoka/figlet /tmp/figlet$$ >/dev/null 2>&1
     cd /tmp/figlet$$
     sudo make install
     cd "${HERE}"
@@ -247,7 +298,7 @@ install_ranger() {
   have_make=$(type -p make)
   if [ "${have_make}" ]; then
     HERE=$(pwd)
-    git clone https://github.com/ranger/ranger /tmp/ranger$$
+    git clone https://github.com/ranger/ranger /tmp/ranger$$ >/dev/null 2>&1
     cd /tmp/ranger$$
     git checkout stable
     sudo make install
@@ -477,6 +528,25 @@ install_kitty() {
   }
 }
 
+upgrade_kitty_control() {
+  KC_REPO="https://github.com/doctorfree/kitty-control"
+  git clone ${KC_REPO} /tmp/kctmp$$ >/dev/null 2>&1
+  [ -f /tmp/kctmp$$/install ] || {
+    printf "\nERROR: unable to download kitty-control repository\n"
+    if [ "$1" == "noexit" ]; then
+      prompt_continue
+    else
+      exit 1
+    fi
+  }
+  chmod 755 /tmp/kctmp$$/install
+  /tmp/kctmp$$/install
+  rm -rf /tmp/kctmp$$
+  install_version=$(get_install_version)
+  VERSION=$(echo ${install_version} | awk -F 'r' '{ print $1 }' | sed -e "s/v//")
+  RELEASE=$(echo ${install_version} | awk -F 'r' '{ print $2 }')
+}
+
 prompt_continue() {
   if [ "${have_rich}" ]; then
     rich "Press [magenta]<Enter>[/] to continue ... " -p
@@ -682,7 +752,7 @@ show_usage() {
     else
       brief_usage noexit
     fi
-    printf "\n\n"
+    show_versions
     options=()
     PS3="${BOLD}Enter a choice (number, shortcut, or text, 'h' help): ${NORM}"
     options+=("Examples" "Full Usage" "Main Menu" "Quit (q)")
@@ -745,9 +815,25 @@ show_menu() {
     }
     options+=("Show Usage Message" "Theme Selection")
     options+=("Terminal Info" "Toggle Fullscreen" "Transparent" "Unicode Input")
-    update_kitty=$(check_kitty_version)
-    [ "${update_kitty}" ] && options+=("Upgrade Kitty (${install_version} -> ${release_version})")
+    release_version=$(curl -fsSL "https://sw.kovidgoyal.net/kitty/current-version.txt")
+    install_version=$(kitty --version | awk '{ print $2 }')
+    update_kitty=$(check_kitty_version "${release_version}" "${install_version}")
+    [ "${update_kitty}" ] && {
+      options+=("Upgrade Kitty (${install_version} -> ${release_version})")
+    }
+    control_version=$(get_control_version)
+    install_version=$(get_install_version)
+    update_control=$(check_control_version "${control_version}" "${install_version}")
+    [ "${update_control}" ] && {
+      options+=("Upgrade kitty-control (${install_version} -> ${control_version})")
+    }
     options+=("View an Image" "Quit (q)")
+    shortcuts="d/dark F/full f/font i/info L/list l/load T/theme t/tran v/view"
+    if [ "${have_rich}" ]; then
+      rich "[b cyan]Shortcuts:[/] [b yellow]${shortcuts}[/]" -p
+    else
+      printf "\nShortcuts: ${BOLD}${shortcuts}${NORM}\n"
+    fi
     select opt in "${options[@]}"; do
       case "$opt,$REPLY" in
       "h",* | *,"h" | "H",* | *,"H" | "help",* | *,"help" | "Help",* | *,"Help")
@@ -965,7 +1051,11 @@ show_menu() {
         man kitty-control
         break
         ;;
-      "Upgrade"*,* | *,"Upgrade"* | "upgrade"*,* | *,"upgrade"*)
+      "Upgrade kitty-control"*,* | *,"Upgrade kitty-control"* | "upgrade kitty-control"*,* | *,"upgrade kitty-control"*)
+        upgrade_kitty_control noexit
+        break
+        ;;
+      "Upgrade Kitty"*,* | *,"Upgrade Kitty"* | "upgrade kitty"*,* | *,"upgrade kitty"*)
         install_kitty
         break
         ;;
@@ -1212,11 +1302,21 @@ while [[ $1 ]]; do
       shift
       ;;
     upgrade|--upgrade)
-      update_kitty=$(check_kitty_version)
+      release_version=$(curl -fsSL "https://sw.kovidgoyal.net/kitty/current-version.txt")
+      install_version=$(kitty --version | awk '{ print $2 }')
+      update_kitty=$(check_kitty_version "${release_version}" "${install_version}")
       if [ "${update_kitty}" ]; then
         install_kitty
       else
         printf "\nInstalled version of Kitty is current ✨ 🌟 ✨\n"
+      fi
+      control_version=$(get_control_version)
+      install_version=$(get_install_version)
+      update_control=$(check_control_version "${control_version}" "${install_version}")
+      if [ "${update_control}" ]; then
+        upgrade_kitty_control
+      else
+        printf "\nInstalled version of kitty-control is current ✨ 🌟 ✨\n"
       fi
       shift
       ;;
