Add option to specify logo file in nfetch, add support for Fedora, fix image filename in fastfetch configs during install

diff --git a/neofetch/nfetch b/neofetch/nfetch
--- a/neofetch/nfetch
+++ b/neofetch/nfetch
@@ -7,8 +7,9 @@
 #
 # Author: Ronald Joe Record <ronaldrecord@gmail.com>
 #
-# Usage: ffetch/nfetch [-c config] [-r] [-u]
+# Usage: ffetch/nfetch [-a] [-c config] [-r] [-u]
 # Where:
+#   -a indicates use ascii logo with neofetch
 # 	-c 'config' specifies a configuration file to use
 # 	  'config' can be the full path or name of a configuration
 # 	-r indicates select configuration file randomly
@@ -17,45 +18,51 @@
 IMG="${HOME}/.local/share/icons/hicolor/__SIZE__x__SIZE__/apps/__PLATFORM__.png"
 FETCHARGS=
 
-me=$(basename "$0")
+prog_name=$(basename "$0")
 have_fastfetch=$(type -p fastfetch)
 have_neofetch=$(type -p neofetch)
-if [ "${me}" == "nfetch" ]; then
-  if [ "${have_neofetch}" ]; then
-    FETCH="neofetch"
-    [ -f "${IMG}" ] && FETCHARGS="--kitty ${IMG}"
-  else
-    if [ "${have_fastfetch}" ]; then
-      FETCH="fastfetch"
-    else
-      printf "\nCannot locate neofetch. Exiting.\n\n"
-      exit 1
-    fi
-  fi
-else
-  FETCH="fastfetch"
-  [ "${have_fastfetch}" ] || {
-    if [ "${have_neofetch}" ]; then
-      FETCH="neofetch"
-      [ -f "${IMG}" ] && FETCHARGS="--kitty ${IMG}"
-    else
-      printf "\nCannot locate fastfetch. Exiting.\n\n"
-      exit 1
-    fi
-  }
-fi
-
-CONFDIR="${XDG_CONFIG_HOME:-${HOME}/.config}/${FETCH}"
 
 usage() {
-  printf "\nUsage: ${me} [-a] [-c config] [-r] [-u]"
+  printf "\nUsage: ${prog_name} [-a] [-c config] [-i /path/to/logo] [-r] [-u]"
   printf "\nWhere:"
   printf "\n\t-a indicates use ascii logo with neofetch"
   printf "\n\t-c 'config' specifies a configuration file to use"
   printf "\n\t   'config' can be the full path or name of a configuration"
+  printf "\n\t-i '/path/to/logo' specifies an image for neofetch to use"
   printf "\n\t-r indicates select configuration file randomly"
   printf "\n\t-u displays this usage messge and exits\n\n"
   exit 1
+}
+
+set_fetch() {
+  if [ "${prog_name}" == "nfetch" ]; then
+    if [ "${have_neofetch}" ]; then
+      FETCH="neofetch"
+      [ -f "${IMG}" ] && {
+        [ "${USE_ASCII}" ] || FETCHARGS="--kitty ${IMG}"
+      }
+    else
+      if [ "${have_fastfetch}" ]; then
+        FETCH="fastfetch"
+      else
+        printf "\nCannot locate neofetch. Exiting.\n\n"
+        exit 1
+      fi
+    fi
+  else
+    FETCH="fastfetch"
+    [ "${have_fastfetch}" ] || {
+      if [ "${have_neofetch}" ]; then
+        FETCH="neofetch"
+        [ -f "${IMG}" ] && {
+          [ "${USE_ASCII}" ] || FETCHARGS="--kitty ${IMG}"
+        }
+      else
+        printf "\nCannot locate fastfetch. Exiting.\n\n"
+        exit 1
+      fi
+    }
+  fi
 }
 
 get_rand() {
@@ -72,15 +79,19 @@ get_rand() {
   USE_CONFIG=${configs[${seconds} % ${#configs[@]}]}
 }
 
+USE_ASCII=
 USE_RANDOM=
 USE_CONFIG=
-while getopts ":ac:ru" flag; do
+while getopts ":ac:i:ru" flag; do
   case $flag in
     a)
-      FETCHARGS=
+      USE_ASCII=1
       ;;
     c)
       USE_CONFIG="$OPTARG"
+      ;;
+    i)
+      [ -f "$OPTARG" ] && IMG="$OPTARG"
       ;;
     r)
       USE_RANDOM=1
@@ -100,6 +111,9 @@ shift $(( OPTIND - 1 ))
   printf "\nIncompatible options: -r cannot be used with -c config. Exiting.\n\n"
   exit 1
 }
+
+set_fetch
+CONFDIR="${XDG_CONFIG_HOME:-${HOME}/.config}/${FETCH}"
 
 tput clear
 export TERM=xterm-kitty
